name: Create distribution

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: node:16-bookworm-slim
    steps:
      - name: Get dependencies
        run: >-
          echo 'deb http://deb.debian.org/debian bookworm-backports main' >> /etc/apt/sources.list.d/backports.list &&
          apt-get update &&
          apt-get install -y
          acl
          git
          gcc
          pkg-config
          libwayland-dev
          wayland-protocols/bookworm-backports
          libxcb1-dev
          libacl1-dev
        if: ${{ runner.os == 'Linux' }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: https://github.com/actions/setup-go@v5
        with:
          go-version: '>=1.23.0'

      - name: Go generate
        run: >-
          go generate ./...

      - name: Build for release
        run: FORTIFY_VERSION='${{ github.ref_name }}' ./dist/release.sh

      - name: Release
        id: use-go-action
        uses: https://gitea.com/actions/release-action@main
        with:
          files: |-
            dist/fortify-**
          api_key: '${{secrets.RELEASE_TOKEN}}'
